set B (set_color blue)
set BR (set_color --bold red)
set BG (set_color --bold green)
set BB (set_color --bold blue)
set BY (set_color --bold yellow)
set BC (set_color --bold cyan)
set BW (set_color --bold white)
set BO (echo -ne "\033[38;5;202m\033[1m")
set RESET (set_color normal)
